### ISSUE TITLE
Upgrading to Elm 0.18

### ISSUE THREAD

**Issue by fpapado** [exercism/xelm#122]
Now that Elm 0.18 is out, is upgrading the exercises desirable? This is probably not critical, since by default we ask users to:
`$ npm install --global elm@0.17.1 elm-test@0.17.3`
thus 0.17 is always the one run as far as exercism is concerned.
Regardless, I hope to outline the considerations about upgrading and start a discussion about how we handle it.

# Issues
## Version Compatibility
While the version bump in elm is minor, the accompanying packages all have major bumps
Thus, if we simply change the version line in elm-package.json to:
`"elm-version": "0.18.0 <= v < 0.19.0`

It works, but the other packages require major version bumps:
```
Error: I cannot find a set of packages that works with your constraints.

--> Your elm-package.json has the following dependency:
    
        "elm-lang/core": "4.0.0 <= v < 5.0.0"
    
    But none of the versions in that range work with Elm 0.18.0. I recommend
    removing that dependency by hand and adding it back with:
    
        elm-package install elm-lang/core 5.0.0

--> Your elm-package.json has the following dependency:
    
        "elm-community/elm-test": "2.0.0 <= v < 3.0.0"
    
    But none of the versions in that range work with Elm 0.18.0. I recommend
    removing that dependency by hand and adding it back with:
    
        elm-package install elm-community/elm-test 3.0.0
```

As far as I can tell, simply upgrading to 0.18 with the suggestions above would preclude backwards-compatibility with someone using 0.17, since the following change cannot be satisfied with 0.17:
```
        "elm-lang/core": "4.0.0 <= v < 5.0.0"
        "elm-lang/core": "5.0.0 <= v < 6.0.0"
```
Fair enough, to keep compatibility, we could do:
```
        "elm-lang/core": "4.0.0 <= v < 6.0.0",
[...]
        "elm-version": "0.17.0 <= v <  0.19.0
```
This will be satisfied with ```elm-lang/core 5.0.0``` in 0.18 and ```elm-lang/core 4.0.5``` in 0.17.

## Test Compatibility
The above seems nice in keeping both 0.17 and 0.18 for people, but our *Test.elm files are still going to be written in one style or the other. While the syntax changes in Elm are small, the changes in the packages that receive major version bumps might be larger. This is already the case with function signature changes in elm-test. It seems that we would have to move to 0.18 as a whole.

# Worked Example
The steps are pretty much described in https://github.com/elm-lang/elm-platform/blob/master/upgrade-docs/0.18.md

In addition to that:
1. Bump elm-version, either to 0.18.0 as minimum or 0.17.0 as minimum
2. Depending on our choice above, bump core, test and anything that complains about not being satisfiable with 0.18. If we're keeping 0.17, keep the lower bound as well.
3. Test that everything works, essentially the test files.
4. It might not be possible to have the test file run in both versions, due to package changes.

For instance, changing the pangram exercise to handle both:
```
{
    "version": "3.0.0",
    "summary": "Exercism problems in Elm.",
    "repository": "https://github.com/exercism/xelm.git",
    "license": "BSD3",
    "source-directories": [
        "."
    ],
    "exposed-modules": [],
    "dependencies": {
        "elm-lang/core": "4.0.0 <= v < 6.0.0",
        "elm-community/elm-test": "2.0.0 <= v < 4.0.0",
        "rtfeldman/node-test-runner": "2.0.0 <= v < 4.0.0"
    },
    "elm-version": "0.17.0 <= v < 0.19.0"
}
```
throws the error:
```
The definition of `main` does not match its type annotation.

52| main : Program Value
53| main =
54|>    run emit tests

The type annotation for `main` says it is a:

    Program Value

But the definition (shown above) is a:

    Test.Runner.Node.TestProgram
```
Sure enough, changing it makes it work in 0.18 and related packages, but breaks 0.17:
```
-- NAMING ERROR ----------------------------------------------- PangramTests.elm

Cannot find type `Test.Runner.Node.TestProgram`.

52| main : Test.Runner.Node.TestProgram
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The qualifier `Test.Runner.Node` is not in scope. 
```
I haven't run through all the exercises, but I expect to find errors like that in many of them.

# Lingering Questions
- You might argue that, for small changes, the update process is unnecessary. In that case, let's just have the discussion for the future.
- Elm avoids major bumps to the language itself, but the core packages are quite liberal about major bumps. Do we always upgrade to the latest once a new Elm version is out?
- How do we notify users to update their setup to 0.18, if we do decide to upgrade?
- How do other exercism languages handle this?

This is recent, so I might have missed something; please be gentle if that is the case.
If we do decide to upgrade to 0.18, I'm willing to help!

**Comment by ryanplant-au** [comment]
If the exercises aren't updated to the latest version consistently, I think @mattludwigs' new [Elm version manager](https://github.com/mattludwigs/elm-version-manager) should be linked in the READMEs. Elm's updates so far have made pretty radical changes to fundamental features and syntax compared to other languages so it's likely to be a problem -- I know it was for me.

**Comment by tgecho** [comment]
Thanks for working through so much of this! I'm afraid we (I) didn't handle the 0.16 -> 0.17 transition very smoothly, and I've had even less time lately to think about this one.

One option might be to add a minimal `package.json` to each exercise along the lines of

```
{
  "scripts": {
    "test": "elm package install && elm-test *Tests.elm"
  },
  "dependencies": {
    "elm": "^0.18.0",
    "elm-test": "^0.18.0"
  }
}
```

We already have a node dependency due to `elm-test`. Running `npm install` followed by `npm test` would actually run the version of elm in the local `node_modules` folder, allowing it to not conflict with the global version.

If this solution is acceptable (and is shown to work on windows), the main question that remains is how to communicate it. Maybe add a tiny `HOW_TO_RUN_TESTS.txt` file to each exercise? 😄

**Comment by rebelwarrior** [comment]
Hi,
I seem to not be able to run tests, even when I try to change the Test file to upgrade it. This is the error I get no matter what I do. 
```
[stdin]:12413
    if (typeof Elm === "undefined") { throw "elm-io config error: Elm is not defined. Make sure you call elm-io with a real Elm output file"}
                                      ^
elm-io config error: Elm is not defined. Make sure you call elm-io with a real Elm output file
```

**Comment by rebelwarrior** [comment]
The problem above seems to have gone away with elm-test 0.18.2

**Comment by rebelwarrior** [comment]
Recommend we use **yarn** for package management. This would allow easy installation of packages and keep them local to each test and future proof (at least to some degree) for future updates.

**Comment by tgecho** [comment]
@rebelwarrior I'm fond of Yarn myself. Though I haven't used it enough to be sure, my understanding is that it should be drop in compatible with npm for our purposes. In other words, we could make a `package.json` and tell people to `npm install` or `yarn install` and everything should work.
